model:
  name: lightgcn # lightgcn,hccf
  num_layers: 3
  hidden_size: 64
  p_dropout: 0.0
  embedding_config:
    name: dhe
    hidden_sizes: [256, 256, 128, 128]

train_dataloader:
  dataset:
    path: dataset/cf/yelp2018/model_train.txt
    adj_style: lightgcn # lightgcn or hccf
    sampling_method: popularity
  num_workers: 4
  batch_size: 2048

val_dataloader:
  dataset:
    path: dataset/cf/yelp2018/model_val.txt
  batch_size: 2048
  num_workers: 4

test_dataloader:
  dataset:
    path: dataset/cf/yelp2018/test.txt
  batch_size: 2048
  num_workers: 4

run_test: false

checkpoint_path: checkpoints/checkpoint.pth
num_epochs: 5
log_step: 100

weight_decay: 0.0001
info_nce_weight: 0.1
learning_rate: 0.001
validate_step: 1

enable_profile: false

profilers:
  train_profiler:
    log_path: logs/lightgcn/train
    # Check pytorch document on profiler for more information
    # https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html#use-profiler-to-record-execution-events
    schedule:
      wait: 1
      warmup: 1
      active: 3
      repeat: 2
    record_shapes: true
    profile_memory: true
    with_stack: false
  val_profiler:
    log_path: logs/lightgcn/val
    schedule:
      wait: 1
      warmup: 1
      active: 3
      repeat: 2
    record_shapes: true
    profile_memory: true
    with_stack: true

logger:
  level: INFO
  log_folder: logs/original
