model:
  name: lightgcn # lightgcn,hccf
  num_layers: 4
  hidden_size: 64
  p_dropout: 0.0
  embedding_config:
    name: pep_retrain
    ori_weight_dir: "checkpoints/pep_ori"
    checkpoint_weight_dir: "checkpoints/pep_trial/"
    sparsity: target

pep_config:
  target_sparsity: 0.5
  best_checkpoint_dir: checkpoints/best_pep
  model_init_path: checkpoints/model_pep_init.pth
  is_retrain: True
  trial_checkpoint: checkpoints/pep_trial
  weight_decay: 0.05

train_dataloader:
  dataset:
    path: dataset/cf/yelp2018/model_train.txt
    adj_style: lightgcn # lightgcn or hccf
    sampling_method: popularity
  num_workers: 4
  batch_size: 2048

val_dataloader:
  dataset:
    path: dataset/cf/yelp2018/model_val.txt
  batch_size: 2048
  num_workers: 4

test_dataloader:
  dataset:
    path: dataset/cf/yelp2018/test.txt
  batch_size: 2048
  num_workers: 4

run_test: false

checkpoint_path: checkpoints/checkpoint.pth
num_epochs: 40
log_step: 100

weight_decay: 0.005
# weight_decay: 0.01
info_nce_weight: 0.5
learning_rate: 0.01
validate_step: 1

enable_profile: false

profilers:
  train_profiler:
    log_path: logs/lightgcn/train
    # Check pytorch document on profiler for more information
    # https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html#use-profiler-to-record-execution-events
    schedule:
      wait: 1
      warmup: 1
      active: 3
      repeat: 2
    record_shapes: true
    profile_memory: true
    with_stack: false
  val_profiler:
    log_path: logs/lightgcn/val
    schedule:
      wait: 1
      warmup: 1
      active: 3
      repeat: 2
    record_shapes: true
    profile_memory: true
    with_stack: true

logger:
  level: INFO
  log_folder: logs/pep-debug/
  log_name: sglwa-initthreshold-6.5-decay1e-3
