model:
  num_factor: 16
  hidden_sizes:
    - 400
    - 400
    - 400
  p_dropout: 0.2
  use_batchnorm: True
  embedding_config:
    name: deepfm_optembed

train_dataloader:
  dataset:
    path: dataset/ctr/criteo/new-ctr/train.txt
    cache_path: dataset/ctr/criteo/criteo-common-split/train.bin
  num_workers: 0
  batch_size: 2048

val_dataloader:
  dataset:
    path: dataset/ctr/criteo/new-ctr/val.txt
    cache_path: dataset/ctr/criteo/criteo-common-split/val.bin
  batch_size: 2048
  num_workers: 0

test_dataloader:
  dataset:
    path: dataset/ctr/criteo/new-ctr/test.txt
    cache_path: dataset/ctr/criteo/criteo-common-split/test.bin
  batch_size: 2048
  num_workers: 0

run_test: false

checkpoint_path: checkpoints/deepfm_checkpoint_opt.pth
num_epochs: 15
log_step: 1000

weight_decay: 0.001
learning_rate: 0.00003
validate_step: 1

enable_profile: false

# Opt Specific config
opt_embed:
  init_weight_path: checkpoints/deepfm/opt/initial.pth
  t_param_lr: 0.0001
  alpha: 0.0001

profilers:
  train_profiler:
    log_path: logs/lightgcn/train
    # Check pytorch document on profiler for more information
    # https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html#use-profiler-to-record-execution-events
    schedule:
      wait: 1
      warmup: 1
      active: 3
      repeat: 2
    record_shapes: true
    profile_memory: true
    with_stack: false
  val_profiler:
    log_path: logs/lightgcn/val
    schedule:
      wait: 1
      warmup: 1
      active: 3
      repeat: 2
    record_shapes: true
    profile_memory: true
    with_stack: true

logger:
  level: INFO
  log_folder: logs/deepfm
  log_name: opt-embed
