model:
  num_layers: 3
  hidden_size: 64

train_dataset:
  path: dataset/cf/gowalla/train.txt
  num_workers: 4
  batch_size: 2048

test_dataset:
  path: dataset/cf/gowalla/test.txt
  batch_size: 2048

checkpoint_path: checkpoints/checkpoint.pth
num_epochs: 1000
log_step: 100

weight_decay: 0.0001
learning_rate: 0.001
