model:
  name: lightgcn # lightgcn or hccf
  num_layers: 3
  hidden_size: 64

train_dataloader:
  dataset:
    path: dataset/cf/gowalla/train.txt
    adj_style: lightgcn # lightgcn or hccf
  num_workers: 4
  batch_size: 2048

test_dataloader:
  dataset:
    path: dataset/cf/gowalla/test.txt
  batch_size: 2048
  num_workers: 4

checkpoint_path: checkpoints/checkpoint.pth
num_epochs: 3
log_step: 100

weight_decay: 0.0001
learning_rate: 0.001
validate_step: 10

enable_profile: false

profilers:
  train_profiler:
    log_path: logs/lightgcn/train
    # Check pytorch document on profiler for more information
    # https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html#use-profiler-to-record-execution-events
    schedule:
      wait: 1
      warmup: 1
      active: 3
      repeat: 2
    record_shapes: true
    profile_memory: true
    with_stack: false
  val_profiler:
    log_path: logs/lightgcn/val
    schedule:
      wait: 1
      warmup: 1
      active: 3
      repeat: 2
    record_shapes: true
    profile_memory: true
    with_stack: true

logger:
  level: INFO
  log_folder: logs/lightgcn
